logger:
  level: "info"
  preset: "production"
storage:
  type: "sql"
  hostname: localhost
  dbname: calendardb
  port: 5432
  username: postgres
  password: changeme
http:
  hostname: "0.0.0.0"
  port: "8080"